# Generated by Django 5.2.3 on 2026-03-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Континент')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🌍', max_length=50)),
            ],
            options={
                'verbose_name': 'Континент',
                'verbose_name_plural': 'Континенти',
            },
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('extreme', 'Екстремно'), ('family', 'Семейно'), ('budget', 'Бюджетно'), ('luxury', 'Луксозно'), ('adventure', 'Приключенско'), ('cultural', 'Културно'), ('beach', 'Плажно'), ('mountain', 'Планинско')], max_length=50, unique=True)),
                ('icon', models.CharField(default='✈️', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип пътуване',
                'verbose_name_plural': 'Типове пътувания',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Държава')),
                ('slug', models.SlugField(unique=True)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='categories.continent')),
            ],
            options={
                'verbose_name': 'Държава',
                'verbose_name_plural': 'Държави',
                'ordering': ['name'],
            },
        ),
    ]
