# Generated by Django 5.2.3 on 2026-03-16 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/covers/')),
                ('body', models.TextField(verbose_name='Съдържание')),
                ('location_name', models.CharField(max_length=200, verbose_name='Локация')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='categories.country')),
                ('travel_types', models.ManyToManyField(blank=True, related_name='posts', to='categories.traveltype', verbose_name='Типове пътуване')),
            ],
            options={
                'verbose_name': 'Пътепис',
                'verbose_name_plural': 'Пътеписи',
                'ordering': ['-created_at'],
            },
        ),
    ]
